name: neetprep_essential
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.1.35+221

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  lottie: ^1.2.2
  auto_size_text: 3.0.0
  cached_network_image: ^3.2.3
  confetti: ^0.7.0
  csslib: ^0.17.3
  device_info_plus: ^9.1.2
  device_info_plus_platform_interface: 7.0.0
  flutter_keyboard_visibility: ^5.0.3
  dio: ^5.3.3
  dropdown_button2: ^2.3.9
  easy_debounce: ^2.0.3
  equatable: 2.0.5
  expandable: 5.0.1
  firebase_auth: ^4.9.0
  firebase_auth_platform_interface: ^6.18.0
  firebase_auth_web: ^5.8.0
  firebase_core: ^2.15.1
  firebase_core_platform_interface: 4.8.0
  firebase_core_web: ^2.7.0
  firebase_crashlytics: ^3.3.5
  firebase_crashlytics_platform_interface: ^3.6.5
  firebase_messaging: ^14.6.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_cache_manager: ^3.3.1
  flutter_html: ^3.0.0-beta.2
  flutter_html_audio: ^3.0.0-beta.2
  flutter_html_iframe: ^3.0.0-beta.2
  flutter_html_math: ^3.0.0-beta.2
  flutter_html_svg: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_html_video: ^3.0.0-beta.2
  flutter_inappwebview: 6.0.0
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.2.7
  flutter_svg: ^2.0.7
  fluttertoast: 8.0.9
  font_awesome_flutter: ^10.5.0
  from_css_color: 2.0.0
  go_router: ^10.1.2
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.5
  google_sign_in_android: ^6.1.18
  google_sign_in_ios: ^5.6.3
  google_sign_in_platform_interface: ^2.4.2
  google_sign_in_web: ^0.12.0+5
  in_app_review: ^2.0.6
  infinite_scroll_pagination:
    git:
      url: https://github.com/FlutterFlow/infinite_scroll_pagination.git
      ref: develop
  internet_file: ^1.2.0
  intl: ^0.19.0
  json_path: ^0.6.3
  js: ^0.6.2
  mime_type: 1.0.0
  page_transition: ^2.0.9
  path_provider: ^2.1.1
  path_provider_android: ^2.2.0
  path_provider_foundation: ^2.3.1
  path_provider_platform_interface: ^2.1.1
  paytm_allinonesdk: ^1.2.8
  pdfx: ^2.6.0
  plugin_platform_interface: ^2.1.6
  pointer_interceptor: ^0.9.3+6
  provider: ^6.0.5
  rxdart: 0.27.7
  share_plus: ^7.1.0
  shared_preferences: ^2.2.1
  shared_preferences_android: ^2.2.1
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: ^2.3.1
  shared_preferences_web: ^2.2.1
  sign_in_with_apple: ^5.0.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.0
  syncfusion_flutter_pdfviewer: ^24.2.6
  text_search: 0.0.2
  timeago: ^3.5.0
  universal_html: ^2.2.1
  url_launcher: ^6.1.14
  url_launcher_android: ^6.1.0
  url_launcher_ios: ^6.1.5
  url_launcher_platform_interface: ^2.1.5
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.9.5
  webview_flutter_platform_interface: ^2.5.1
  webview_flutter_web: ^0.2.2+1
  webview_flutter_wkwebview: ^3.7.4
  youtube_player_iframe: 4.0.4
  firebase_analytics: ^10.5.0
  upgrader: ^8.4.0
  new_version_plus: ^0.0.11
  in_app_update: ^4.2.2
  flip_card: ^0.7.0
  firebase_performance: ^0.9.2+7
  buttons_tabbar: ^1.3.8
  flutter_math_fork: 0.7.2
  internet_connection_checker: ^1.0.0+1
  file_picker: ^6.2.0
  screen_protector: ^1.4.2
  package_info_plus: ^4.2.0
  just_the_tooltip: ^0.0.12
  showcaseview: ^2.0.3
  carousel_slider: ^4.2.1
  flutter_image_slideshow: any
  webview_cookie_manager: ^2.0.2
  rename: ^2.0.1
  table_calendar: ^3.0.9
  fl_chart: ^0.68.0
  cloud_firestore: ^4.9.3
  clevertap_plugin: 3.0.0
  firebase_in_app_messaging: ^0.7.3+7
  uni_links: ^0.5.1

dependency_overrides:
  flutter_math_fork: 0.7.2
  http: 1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_launcher_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/webpage.html

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
