// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkCwHfmBau9fiWl2jT-XFiyWhd5D4nfbk',
    appId: '1:623494990675:web:b0c2b9f992f35938af2fa6',
    messagingSenderId: '623494990675',
    projectId: 'neetprep-essential',
    authDomain: 'neetprep-essential.firebaseapp.com',
    storageBucket: 'neetprep-essential.appspot.com',
    measurementId: 'G-BQXRP3W5QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1JrKSciEFsIDXorv8DMHLWxv_K3PgXN4',
    appId: '1:623494990675:android:d2ae1ba7f231b81baf2fa6',
    messagingSenderId: '623494990675',
    projectId: 'neetprep-essential',
    storageBucket: 'neetprep-essential.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPnDx4rOFgC4vQXZeqTyc4GMP-xQDFmTc',
    appId: '1:545751718198:ios:0ad53ca21295b77e58fb97',
    messagingSenderId: '545751718198',
    projectId: 'neetprepios',
    storageBucket: 'neetprepios.firebasestorage.app',
    iosClientId: '545751718198-vuf6jdbui14uhcetonj1j2lob1k76jmh.apps.googleusercontent.com',
    iosBundleId: 'com.neetprep.ios',
  );

}